### ISSUE TITLE
Add support for notify popup graphic

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-hint#16]
This was an item raised in #13 which I think needs further input so I'm raising this as a separate issue. Looking at the existing graphic support in notify popups is handled differently in Adapt.

**Core notify** renders the graphic within the [`.notify__section`](https://github.com/adaptlearning/adapt-contrib-core/blob/2c455d7b5cf3c52c4457378d3c6c30b800b2d8c1/templates/notifyPopup.hbs#L30) with the positioning dependant on the `_imageAlignment` (whether to render before or after `.notify__body`). See screenshot below.

<img width="1295" alt="tutor-popup" src="https://github.com/cgkineo/adapt-hint/assets/7045330/1a09ced7-941d-4521-b87e-467931317bd1">

**Hotgraphic** and **Hotgrid** don't render the graphic within `.notify__section`, instead this is just an empty element. The difference being these components use their own popup templates. In addition, the positioning `_imageAlignment` is handled via [CSS flex styles](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/63a02f77bf6b9e87a754fad8cd4d1649250a131a/less/hotgraphicPopup.less#L87) instead of setting the DOM order. See screenshot below.

<img width="1480" alt="hotgraphic-popup" src="https://github.com/cgkineo/adapt-hint/assets/7045330/dbb53862-b0b2-4e86-8288-e0fba6dc451e">

Worth noting, although the implementation is handled differently, the graphic config is consistent e.g. question `_feedback`, Hotgraphic and Hotgrid `_items`.

```
      "_imageAlignment": "right",
      "_graphic": {
          "src": "course/en/images/example.jpg",
          "alt": "",
          "attribution": "",
          "_classes": ""
      }
```

Thoughts on how we should go about this? 

An ideal for me, we wouldn't have popup templates in plugins or at least not for the properties shared across notify popups. Although this is a bigger issue than Hint as it would be good to uniform this across the plugins. 

In regard to `_imageAlignment`, I'd be in favour of setting the DOM order instead of using CSS flex styles as this is better a11y.

**Comment by danielghost** [comment]
@kirsty-hames  - to look at and raise any issues on core that are required.

**Comment by oliverfoster** [comment]
Thoughs:

I don't think it's a good idea to move all of the behaviour from the hotgraphic/hotgrid into the core.

I had always thought of notify as just a container for other things. The hotgraphic and hotgrid should share a view class really, their left/right narrative items view, and each plugin should then put its instance in the notify. This gives maximum flexibility to use the notify for any kind of sub view.

That the notify has its own template for title, body and graphic was kind of inconsequential to me.

**Comment by oliverfoster** [comment]
Suggest using core notify template https://github.com/adaptlearning/adapt-contrib-core/blob/master/templates/notifyPopup.hbs instead of a sub view, that will give images to hint.

https://github.com/cgkineo/adapt-hint/blob/bab0d045e19e858e29ae1fd556469a1a0a5fd6a4/js/adapt-hint.js#L57-L60

```js
 Adapt.notify.popup({ 
   ...this.model.get('_hint'),
   _classes: 'hint-popup' 
 }); 
```

Open issue on hotgraphic and hotgrid about use of flex.

Perhaps open issue on core to stop notify__section appearing when not _graphic.src and body https://github.com/adaptlearning/adapt-contrib-core/blob/535905f91b1dfca190179f6e6ef2909e020f0efb/templates/notifyPopup.hbs#L30

**Comment by kirsty-hames** [comment]
> Suggest using core notify template https://github.com/adaptlearning/adapt-contrib-core/blob/master/templates/notifyPopup.hbs instead of a sub view, that will give images to hint.
> 
> https://github.com/cgkineo/adapt-hint/blob/bab0d045e19e858e29ae1fd556469a1a0a5fd6a4/js/adapt-hint.js#L57-L60
> 
> ```js
>  Adapt.notify.popup({ 
>    ...this.model.get('_hint'),
>    _classes: 'hint-popup' 
>  }); 
> ```

I've tried implementing this but `_imageAlignment` and `_graphic` aren't available settings for the 'popup' `notifyObject`.  Is this because it was only made available to QuestionModel as per the initial Core PR https://github.com/adaptlearning/adapt-contrib-core/pull/223 ?

**Comment by oliverfoster** [comment]
> `_imageAlignment and _graphic aren't available settings for the 'popup'` 

What do you mean that they aren't available? Do you mean in the AAT?

It should be a case of adding this to the json:
```js
"_hint": {
 "title": "Adapt Hint",
 "altTitle": "Alt Hint title text",
 "body": "An extension that adds a small, clickable icon to a component that displays additional information.",
 "_imageAlignment": "bottom",
 "_graphic": {
   "_src": "../image.jpg"
  }
}
```

**Comment by kirsty-hames** [comment]
> > `_imageAlignment and _graphic aren't available settings for the 'popup'`
> 
> What do you mean that they aren't available? Do you mean in the AAT?
> 
> It should be a case of adding this to the json:
> 
> ```js
> "_hint": {
>  "title": "Adapt Hint",
>  "altTitle": "Alt Hint title text",
>  "body": "An extension that adds a small, clickable icon to a component that displays additional information.",
>  "_imageAlignment": "bottom",
>  "_graphic": {
>    "_src": "../image.jpg"
>   }
> }
> ```

Nope, just a FW setup with the json as per your example. 

When I open a Hint popup, the `title` and `body` display but the image does not. I assumed this was because `_imageAlignment` and `_graphic` aren't existing settings within the `notifyObject`. See existing settings below.

`NotifyView.popup(notifyObject: { title: string; body: string; _showCloseButton?: boolean; _isCancellable?: boolean; _classes?: string; _view?: Backbone.View<Backbone.Model<any, Backbone.ModelSetOptions, any>, HTMLElement>; })`

So far, `_imageAlignment` and `_graphic` have only been used for question feedback popups which looks to be tied to `QuestionModel` only. I might be barking up the wrong tree but any guidance is appreciated please :)

**Comment by oliverfoster** [comment]
This is where `notify.popup` is called:
https://github.com/adaptlearning/adapt-contrib-core/blob/852ef1269dcdfc220361d500c473c9042ffa65f4/js/views/notifyView.js#L44-L80

This comment does the type definition, for the intellisense in vscode, for that notify object, but it does not include the `_imageAlignment` and `_graphic` properties (it should do though to make coding easier):
https://github.com/adaptlearning/adapt-contrib-core/blob/852ef1269dcdfc220361d500c473c9042ffa65f4/js/views/notifyView.js#L68-L78

This bit passs all of the supplied properties to `notify.popup(object);` though to the view model:
https://github.com/adaptlearning/adapt-contrib-core/blob/852ef1269dcdfc220361d500c473c9042ffa65f4/js/views/notifyView.js#L45-L65

NotifyPopupView then renders all of the properties in the model at:
https://github.com/adaptlearning/adapt-contrib-core/blob/852ef1269dcdfc220361d500c473c9042ffa65f4/js/views/notifyPopupView.js#L62-L75

And the notifyPopup template utilises the `_imageAlignment` and `_graphic` properties if they exist:
https://github.com/adaptlearning/adapt-contrib-core/blob/852ef1269dcdfc220361d500c473c9042ffa65f4/templates/notifyPopup.hbs#L34-L47


>NotifyView.popup(notifyObject: { title: string; body: string; _showCloseButton?: boolean; _isCancellable?: boolean; _classes?: string; _view?: Backbone.View<Backbone.Model<any, Backbone.ModelSetOptions, any>, HTMLElement>; })

I think it might just be the intellisense popup you're referencing? Which are inaccurate in that they don't include `_imageAlignment` and `_graphic` as above.

Are you using `_src` rather than `src`?
https://github.com/adaptlearning/adapt-contrib-core/blob/852ef1269dcdfc220361d500c473c9042ffa65f4/templates/notifyPopup.hbs#L37

Feedback supplies notify with the json config only, it doesn't do anything special otherwise.

**Comment by oliverfoster** [comment]
Try this in the browser console:
```js
require('core/js/notify').popup({
  title: "This is a title",
  body: "this is a body",
  _graphic: { 
    _src: 'course/en/images/menu-item.png'
  },
  _imageAlignment: 'bottom'
});

**Comment by kirsty-hames** [comment]
> This comment does the type definition, for the intellisense in vscode, for that notify object, but it does not include the `_imageAlignment` and `_graphic` properties (it should do though to make coding easier): 

Ah yes, it was the intellisense I was referencing and agree these should be added so it's clear.
 
> Are you using `_src` rather than `src`? 

Doh! Yes I was. All working fine now thanks.
